# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ParkingSpot(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, address: str=None, type: str=None, charger_availability: bool=None):  # noqa: E501
        """ParkingSpot - a model defined in Swagger

        :param id: The id of this ParkingSpot.  # noqa: E501
        :type id: int
        :param address: The address of this ParkingSpot.  # noqa: E501
        :type address: str
        :param type: The type of this ParkingSpot.  # noqa: E501
        :type type: str
        :param charger_availability: The charger_availability of this ParkingSpot.  # noqa: E501
        :type charger_availability: bool
        """
        self.swagger_types = {
            'id': int,
            'address': str,
            'type': str,
            'charger_availability': bool
        }

        self.attribute_map = {
            'id': 'id',
            'address': 'address',
            'type': 'type',
            'charger_availability': 'chargerAvailability'
        }
        self._id = id
        self._address = address
        self._type = type
        self._charger_availability = charger_availability

    @classmethod
    def from_dict(cls, dikt) -> 'ParkingSpot':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParkingSpot of this ParkingSpot.  # noqa: E501
        :rtype: ParkingSpot
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ParkingSpot.


        :return: The id of this ParkingSpot.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ParkingSpot.


        :param id: The id of this ParkingSpot.
        :type id: int
        """

        self._id = id

    @property
    def address(self) -> str:
        """Gets the address of this ParkingSpot.


        :return: The address of this ParkingSpot.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this ParkingSpot.


        :param address: The address of this ParkingSpot.
        :type address: str
        """

        self._address = address

    @property
    def type(self) -> str:
        """Gets the type of this ParkingSpot.


        :return: The type of this ParkingSpot.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ParkingSpot.


        :param type: The type of this ParkingSpot.
        :type type: str
        """

        self._type = type

    @property
    def charger_availability(self) -> bool:
        """Gets the charger_availability of this ParkingSpot.


        :return: The charger_availability of this ParkingSpot.
        :rtype: bool
        """
        return self._charger_availability

    @charger_availability.setter
    def charger_availability(self, charger_availability: bool):
        """Sets the charger_availability of this ParkingSpot.


        :param charger_availability: The charger_availability of this ParkingSpot.
        :type charger_availability: bool
        """

        self._charger_availability = charger_availability
