# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Reservation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, spot_id: int=None, user_id: int=None, start_time: datetime=None, duration: datetime=None, _date: date=None):  # noqa: E501
        """Reservation - a model defined in Swagger

        :param id: The id of this Reservation.  # noqa: E501
        :type id: int
        :param spot_id: The spot_id of this Reservation.  # noqa: E501
        :type spot_id: int
        :param user_id: The user_id of this Reservation.  # noqa: E501
        :type user_id: int
        :param start_time: The start_time of this Reservation.  # noqa: E501
        :type start_time: datetime
        :param duration: The duration of this Reservation.  # noqa: E501
        :type duration: datetime
        :param _date: The _date of this Reservation.  # noqa: E501
        :type _date: date
        """
        self.swagger_types = {
            'id': int,
            'spot_id': int,
            'user_id': int,
            'start_time': datetime,
            'duration': datetime,
            '_date': date
        }

        self.attribute_map = {
            'id': 'id',
            'spot_id': 'spotId',
            'user_id': 'userId',
            'start_time': 'startTime',
            'duration': 'duration',
            '_date': 'date'
        }
        self._id = id
        self._spot_id = spot_id
        self._user_id = user_id
        self._start_time = start_time
        self._duration = duration
        self.__date = _date

    @classmethod
    def from_dict(cls, dikt) -> 'Reservation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Reservation of this Reservation.  # noqa: E501
        :rtype: Reservation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Reservation.


        :return: The id of this Reservation.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Reservation.


        :param id: The id of this Reservation.
        :type id: int
        """

        self._id = id

    @property
    def spot_id(self) -> int:
        """Gets the spot_id of this Reservation.


        :return: The spot_id of this Reservation.
        :rtype: int
        """
        return self._spot_id

    @spot_id.setter
    def spot_id(self, spot_id: int):
        """Sets the spot_id of this Reservation.


        :param spot_id: The spot_id of this Reservation.
        :type spot_id: int
        """

        self._spot_id = spot_id

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Reservation.


        :return: The user_id of this Reservation.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Reservation.


        :param user_id: The user_id of this Reservation.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def start_time(self) -> datetime:
        """Gets the start_time of this Reservation.


        :return: The start_time of this Reservation.
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: datetime):
        """Sets the start_time of this Reservation.


        :param start_time: The start_time of this Reservation.
        :type start_time: datetime
        """

        self._start_time = start_time

    @property
    def duration(self) -> datetime:
        """Gets the duration of this Reservation.


        :return: The duration of this Reservation.
        :rtype: datetime
        """
        return self._duration

    @duration.setter
    def duration(self, duration: datetime):
        """Sets the duration of this Reservation.


        :param duration: The duration of this Reservation.
        :type duration: datetime
        """

        self._duration = duration

    @property
    def _date(self) -> date:
        """Gets the _date of this Reservation.


        :return: The _date of this Reservation.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this Reservation.


        :param _date: The _date of this Reservation.
        :type _date: date
        """

        self.__date = _date
